# Generated by Django 2.2.6 on 2019-10-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentic2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('user_fake_id', models.IntegerField(default=1)),
                ('pair_key', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInformation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(default=1)),
                ('service_key', models.TextField(max_length=20000)),
                ('tpk', models.TextField()),
                ('mk', models.TextField()),
            ],
        ),
    ]
