# Generated by Django 2.2.6 on 2019-10-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation2',
            name='mk',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='baseinformation2',
            name='service_key',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='baseinformation2',
            name='tpk',
            field=models.CharField(max_length=20000),
        ),
    ]
