# Generated by Django 2.2.6 on 2019-10-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_02', '0002_auto_20191010_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation2',
            name='service_key',
            field=models.TextField(max_length=20000),
        ),
    ]
