# Generated by Django 2.2.6 on 2019-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_02', '0004_auto_20191010_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation2',
            name='tpk',
            field=models.TextField(max_length=50000),
        ),
    ]
