# Generated by Django 2.2.6 on 2019-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_01', '0003_auto_20191010_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='mk',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='tpk',
            field=models.TextField(max_length=20000),
        ),
    ]
