# Generated by Django 2.2.6 on 2019-10-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_01', '0006_auto_20191010_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='tpk',
            field=models.TextField(max_length=60000),
        ),
    ]
