# Generated by Django 2.2.6 on 2019-10-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentic',
            name='pair_key',
            field=models.IntegerField(default=20000),
        ),
    ]
